### ISSUE TITLE
Any update on this? 

### ISSUE THREAD

**Issue by rtkwlf-sid** [matrix-io/matrix-creator-nfc-unstable-preview#5]
Not able to download the library from NXP, their servers are always down

**Comment by Hermitter** [comment]
Hey @Sid-CEng! Due to NXP restricting us from uploading their library, you'll need to contact [NXP support](https://www.nxp.com/support/support:SUPPORTHOME) for help with this issue. :slightly_frowning_face:

However, we're currently contacting NXP to request permission for sharing their source code or header files. Adding on to this, we've created a more stable NFC repository that we're planning to officially integrate in the near future.

Repository Link: https://github.com/matrix-io/matrix-hal-nfc
